### ISSUE TITLE
Larger primitives with smaller secrets requires all shares

### ISSUE THREAD

**Issue by zevaryx** [49pctber/shamir#1]
Supplying a large enough primitive causes the program to require all shares with smaller secrets, even when k<n

How to reproduce:

`shamir distribute string -p 1645333507 -k 3 -n 5 "secret"`

The shares:
  shamir-BCZ7H74P-6211cc03-1-W1UuQcsm
  shamir-BCZ7H74P-6211cc03-2-FYcnzrFw
  shamir-BCZ7H74P-6211cc03-3-Pbdq/R8i
  shamir-BCZ7H74P-6211cc03-4-YqmZZ+Hw
  shamir-BCZ7H74P-6211cc03-5-SpnUVE+i

Screenshot of behavior (including it working just fine with the default primitive):

![image](https://github.com/user-attachments/assets/d6e13e71-e882-44dc-a430-881e6e77c058)

Screenshot of a larger secret working fine:

![image](https://github.com/user-attachments/assets/49d157f6-47c8-49c4-90d8-ea05a3c06991)

I assume this is a limitation of how SSS works

**Comment by 49pctber** [comment]
Primitive polynomials must be of degree 8. Supplying a larger primitive polynomial provides no extra security. I'll update it to throw an error.

Edit: this is actually a security vulnerability. If the polynomial is too large, this can leak information about the secret when operating only on bytes. We know the secret byte must be between 0 and 255, inclusive, but a larger polynomial would allow for more possible secrets. This leaks information when we have k-1 shares because we could ignore any possibilities that don't fall in the range of 0-255.

**Comment by 49pctber** [comment]
Should be fixed in ca6e0f8. If the user inputs an incorrect primitive, it will now prompt the user to select one of 8 options. This helped me catch another bug along the way, so thanks for bringing this to my attention.
